"""Enterprise-depth synthetic data — every customer + product carries the
fields a real CRM/ERP would have, and contacts/assets/contracts are linked.
"""

CUSTOMERS = [
    {
        "code": "RTHN-AERO-014",
        "name": "Raytheon Aerospace - El Segundo Lab",
        "legal_entity": "Raytheon Aerospace Inc., El Segundo Operations",
        "region": "AMS",
        "language": "en",
        "email": "rfp.procurement@raytheon-elseg.com",
        "vertical": "aerospace_defense",
        "compliance": ["ITAR", "AS9100", "DFARS_252.204-7012"],
        "industry": "Defense Electronics",
        "naics": "334511",
        "annual_revenue_usd": 28_400_000_000.0,
        "employees": 67_000,
        "account_manager": "Rachel Tomlin",
        "sales_engineer": "Doug Park (RF/EW specialist)",
        "customer_since": "2007-03-12",
        "status": "active",
        "sla_tier": "Platinum",
        "duns": "06-841-2235",
        "tax_id": "95-2293247",
        "payment_terms": "Net 60",
        "credit_limit": 5_000_000.0,
        "default_currency": "USD",
        "default_incoterms": "FOB Origin",
        "addresses": [
            {"type": "headquarters", "line1": "870 Winter Street", "city": "Waltham", "region": "MA", "country": "US", "postal": "02451"},
            {"type": "ship_to", "line1": "2000 East El Segundo Blvd", "line2": "Receiving Dock — Bldg E2", "city": "El Segundo", "region": "CA", "country": "US", "postal": "90245"},
            {"type": "bill_to", "line1": "P.O. Box 11337 — Accounts Payable", "city": "Waltham", "region": "MA", "country": "US", "postal": "02454"},
        ],
        "contacts": [
            {"name": "Mike Ferraro", "title": "Senior Trade Compliance Analyst", "role": "trade_compliance", "email": "trade.compliance@raytheon-elseg.com", "phone": "+1 310 555 0142", "is_primary": True},
            {"name": "Aaron Brewer", "title": "Calibration Lab Supervisor", "role": "lab_ops", "email": "aaron.brewer@raytheon-elseg.com", "phone": "+1 310 555 0177"},
            {"name": "Elaine Park", "title": "Senior Buyer — RF/Microwave", "role": "procurement", "email": "rfp.procurement@raytheon-elseg.com", "phone": "+1 310 555 0144"},
            {"name": "Karen Doyle", "title": "Accounts Payable Lead", "role": "ap", "email": "ap.elseg@raytheon-elseg.com", "phone": "+1 310 555 0119"},
        ],
    },
    {
        "code": "BLUEH-DEF-021",
        "name": "Bluehawk Defense Labs",
        "legal_entity": "Bluehawk Defense & Aerospace LLC",
        "region": "AMS",
        "language": "en",
        "email": "po.intake@bluehawkdefense.com",
        "vertical": "aerospace_defense",
        "compliance": ["ITAR", "EAR", "AS9100"],
        "industry": "Defense Systems Integrator",
        "naics": "334290",
        "annual_revenue_usd": 1_240_000_000.0,
        "employees": 3_200,
        "account_manager": "Patrick Velasquez",
        "sales_engineer": "Luis Ortega",
        "customer_since": "2014-09-22",
        "status": "active",
        "sla_tier": "Gold",
        "duns": "12-447-9981",
        "tax_id": "84-1559022",
        "payment_terms": "Net 45",
        "credit_limit": 1_500_000.0,
        "default_currency": "USD",
        "default_incoterms": "FOB Destination",
        "addresses": [
            {"type": "headquarters", "line1": "4400 N Fairfax Drive", "line2": "Suite 600", "city": "Arlington", "region": "VA", "country": "US", "postal": "22203"},
            {"type": "ship_to", "line1": "Bldg 12 — Calibration Lab", "city": "Arlington", "region": "VA", "country": "US", "postal": "22203"},
        ],
        "contacts": [
            {"name": "Aaron Brewer", "title": "Calibration Lab Supervisor", "role": "lab_ops", "email": "aaron.brewer@bluehawkdefense.com", "phone": "+1 703 555 0181", "is_primary": True},
            {"name": "Marisol Tang", "title": "Procurement Manager", "role": "procurement", "email": "po.intake@bluehawkdefense.com", "phone": "+1 703 555 0102"},
        ],
    },
    {
        "code": "TSMC-FAB-308",
        "name": "Tessera Semiconductor (Foundry 4)",
        "legal_entity": "Tessera Semiconductor Manufacturing Co., Ltd.",
        "region": "APAC",
        "language": "en",
        "email": "metrology.purchasing@tesserasemiconductor.com.tw",
        "vertical": "semiconductor",
        "compliance": ["ISO_17025", "ISO_9001"],
        "industry": "Semiconductor Foundry",
        "naics": "334413",
        "annual_revenue_usd": 76_800_000_000.0,
        "employees": 73_000,
        "account_manager": "Elena Chen",
        "sales_engineer": "Hiroshi Tanaka (Signal Integrity)",
        "customer_since": "2003-05-04",
        "status": "active",
        "sla_tier": "Platinum",
        "duns": "65-770-1244",
        "tax_id": "TW-22099131",
        "payment_terms": "Net 30",
        "credit_limit": 12_000_000.0,
        "default_currency": "USD",
        "default_incoterms": "DDP",
        "addresses": [
            {"type": "headquarters", "line1": "8 Li-Hsin Road 6", "city": "Hsinchu Science Park", "region": "Hsinchu", "country": "TW", "postal": "30078"},
            {"type": "ship_to", "line1": "Foundry 4 — Metrology Bay 12", "city": "Hsinchu Science Park", "region": "Hsinchu", "country": "TW", "postal": "30078"},
        ],
        "contacts": [
            {"name": "Dr. Jen Liu", "title": "Sr. Test Engineering Manager", "role": "lab_ops", "email": "jen.liu@tesserasemiconductor.com.tw", "phone": "+886 3 5555 0144", "is_primary": True},
            {"name": "Daniel Wu", "title": "Metrology Procurement Lead", "role": "procurement", "email": "metrology.purchasing@tesserasemiconductor.com.tw", "phone": "+886 3 5555 0177"},
            {"name": "Liu Mei-Chen", "title": "AP — Foundry Operations", "role": "ap", "email": "ap.fab4@tesserasemiconductor.com.tw", "phone": "+886 3 5555 0188"},
        ],
    },
    {
        "code": "MERID-COMM-077",
        "name": "Meridian Comunicaciones SA",
        "legal_entity": "Meridian Comunicaciones, Sociedad Anónima",
        "region": "EMEA",
        "language": "es",
        "email": "compras.lab@meridiancomms.es",
        "vertical": "wireless_5g6g",
        "compliance": ["ETSI_EN_301", "ISO_9001"],
        "industry": "Wireless Test Lab",
        "naics": "541380",
        "annual_revenue_usd": 184_000_000.0,
        "employees": 620,
        "account_manager": "Carmen Ruiz",
        "sales_engineer": "Pablo Esteban (5G FR2)",
        "customer_since": "2018-11-08",
        "status": "active",
        "sla_tier": "Gold",
        "duns": "44-998-1224",
        "tax_id": "ES-A82345671",
        "payment_terms": "Net 45",
        "credit_limit": 750_000.0,
        "default_currency": "EUR",
        "default_incoterms": "EXW Madrid",
        "addresses": [
            {"type": "headquarters", "line1": "Calle de Serrano 47", "line2": "Planta 5", "city": "Madrid", "region": "MD", "country": "ES", "postal": "28001"},
            {"type": "ship_to", "line1": "Polígono Industrial Alcobendas", "line2": "Nave 22 — Cámara Anecoica", "city": "Alcobendas", "region": "MD", "country": "ES", "postal": "28108"},
        ],
        "contacts": [
            {"name": "Carlos Iglesias", "title": "Lab Operations Lead", "role": "lab_ops", "email": "carlos.iglesias@meridiancomms.es", "phone": "+34 91 555 0144", "is_primary": True, "language": "es"},
            {"name": "Mariela Solís", "title": "Compras Técnicas", "role": "procurement", "email": "compras.lab@meridiancomms.es", "phone": "+34 91 555 0177", "language": "es"},
        ],
    },
    {
        "code": "SAKURA-SEMI-101",
        "name": "Sakura Semiconductor KK",
        "legal_entity": "桜半導体株式会社 / Sakura Semiconductor K.K.",
        "region": "APAC",
        "language": "ja",
        "email": "chumon@sakurasemi.co.jp",
        "vertical": "semiconductor",
        "compliance": ["ISO_17025", "ISO_14001"],
        "industry": "Semiconductor R&D",
        "naics": "334413",
        "annual_revenue_usd": 4_900_000_000.0,
        "employees": 14_500,
        "account_manager": "Kenji Watanabe",
        "sales_engineer": "Akira Sato (mmWave / 5G FR2)",
        "customer_since": "2010-04-01",
        "status": "active",
        "sla_tier": "Platinum",
        "duns": "JP-7720-1144",
        "tax_id": "JP-1234567890123",
        "payment_terms": "Net 30",
        "credit_limit": 8_000_000.0,
        "default_currency": "JPY",
        "default_incoterms": "DDP",
        "addresses": [
            {"type": "headquarters", "line1": "東京都港区赤坂 3-2-12", "line2": "Akasaka Bldg 6F", "city": "Tokyo", "region": "Tokyo", "country": "JP", "postal": "107-0052"},
            {"type": "ship_to", "line1": "横浜市西区みなとみらい 4-3-1", "line2": "桜半導体 R&D センター 受入課", "city": "Yokohama", "region": "Kanagawa", "country": "JP", "postal": "220-0012"},
        ],
        "contacts": [
            {"name": "佐藤 美咲 (Misaki Sato)", "title": "計測機器調達 / Metrology Procurement", "role": "procurement", "email": "chumon@sakurasemi.co.jp", "phone": "+81 3 5555 0144", "is_primary": True, "language": "ja"},
            {"name": "大野 健 (Ken Ohno)", "title": "評価部 シニアエンジニア", "role": "lab_ops", "email": "ohno.k@sakurasemi.co.jp", "phone": "+81 45 555 0177", "language": "ja"},
        ],
    },
    {
        "code": "OZEKI-T&M-088",
        "name": "Ozeki Test Systems",
        "legal_entity": "大関テストシステムズ株式会社",
        "region": "APAC",
        "language": "ja",
        "email": "po@ozekitest.co.jp",
        "vertical": "test_systems_integrator",
        "compliance": ["ISO_9001"],
        "industry": "Test Systems Integration",
        "naics": "541330",
        "annual_revenue_usd": 95_000_000.0,
        "employees": 380,
        "account_manager": "Naoko Iwasaki",
        "sales_engineer": "Tomohiro Kondo",
        "customer_since": "2017-08-15",
        "status": "active",
        "sla_tier": "Silver",
        "duns": "JP-3340-5582",
        "tax_id": "JP-9876543210987",
        "payment_terms": "Net 30",
        "credit_limit": 500_000.0,
        "default_currency": "JPY",
        "default_incoterms": "FCA Tokyo",
        "addresses": [
            {"type": "headquarters", "line1": "東京都品川区西五反田 7-22-17", "city": "Tokyo", "region": "Tokyo", "country": "JP", "postal": "141-0031"},
        ],
        "contacts": [
            {"name": "渡辺 健司 (Kenji Watanabe)", "title": "購買部 Manager", "role": "procurement", "email": "po@ozekitest.co.jp", "phone": "+81 3 5555 0188", "is_primary": True, "language": "ja"},
        ],
    },
    {
        "code": "NORDS-TELCO-045",
        "name": "Nordstern Telecom Labs",
        "legal_entity": "Nordstern Telecommunications GmbH",
        "region": "EMEA",
        "language": "es",
        "email": "pedidos.lab@nordstern-telecom.de",
        "vertical": "wireless_5g6g",
        "compliance": ["ETSI_EN_301", "ISO_9001"],
        "industry": "Telco Lab Services",
        "naics": "541380",
        "annual_revenue_usd": 312_000_000.0,
        "employees": 1_100,
        "account_manager": "Ingrid Jensen",
        "sales_engineer": "Magnus Olsen (RF Conformance)",
        "customer_since": "2016-02-10",
        "status": "active",
        "sla_tier": "Gold",
        "duns": "DE-2299-4471",
        "tax_id": "DE-129273398",
        "payment_terms": "Net 45",
        "credit_limit": 1_200_000.0,
        "default_currency": "EUR",
        "default_incoterms": "DDP",
        "addresses": [
            {"type": "headquarters", "line1": "Friedrichstraße 95", "city": "Berlin", "region": "Berlin", "country": "DE", "postal": "10117"},
            {"type": "ship_to", "line1": "Sigmaringer Str. 12 — Anechoic Lab", "city": "Stuttgart", "region": "BW", "country": "DE", "postal": "70567"},
        ],
        "contacts": [
            {"name": "Lucía Méndez", "title": "AP & Procurement Coordinator", "role": "procurement", "email": "pedidos.lab@nordstern-telecom.de", "phone": "+34 91 555 0244", "is_primary": True, "language": "es"},
            {"name": "Helmut Bauer", "title": "RF Conformance Lead", "role": "lab_ops", "email": "h.bauer@nordstern-telecom.de", "phone": "+49 711 555 0188"},
        ],
    },
    {
        "code": "AURA-AUTO-119",
        "name": "Aurora Automotive Electronics",
        "legal_entity": "Aurora Automotive Electronics, Inc.",
        "region": "AMS",
        "language": "en",
        "email": "ee.procurement@auroraauto.com",
        "vertical": "automotive",
        "compliance": ["IATF_16949", "ISO_26262"],
        "industry": "Automotive Tier-1 Supplier",
        "naics": "336320",
        "annual_revenue_usd": 4_120_000_000.0,
        "employees": 12_400,
        "account_manager": "Jordan Bell",
        "sales_engineer": "Sara Patel (Auto Ethernet)",
        "customer_since": "2012-06-30",
        "status": "active",
        "sla_tier": "Gold",
        "duns": "55-882-9911",
        "tax_id": "38-2871094",
        "payment_terms": "Net 45",
        "credit_limit": 2_500_000.0,
        "default_currency": "USD",
        "default_incoterms": "FOB Destination",
        "addresses": [
            {"type": "headquarters", "line1": "1500 Auburn Hills Drive", "city": "Auburn Hills", "region": "MI", "country": "US", "postal": "48326"},
            {"type": "ship_to", "line1": "EE Lab — Bldg 4 Receiving", "city": "Auburn Hills", "region": "MI", "country": "US", "postal": "48326"},
        ],
        "contacts": [
            {"name": "Danielle Park", "title": "Engineering Procurement", "role": "procurement", "email": "ee.procurement@auroraauto.com", "phone": "+1 248 555 0144", "is_primary": True},
            {"name": "Tom Reilly", "title": "EE Test Lead", "role": "lab_ops", "email": "ee.lead@auroraauto.com", "phone": "+1 248 555 0177"},
        ],
    },
    {
        "code": "VERTEX-Q-053",
        "name": "Vertex Quantum Research",
        "legal_entity": "Vertex Quantum Research Foundation",
        "region": "AMS",
        "language": "en",
        "email": "lab.ops@vertex-quantum.com",
        "vertical": "research",
        "compliance": ["ISO_9001"],
        "industry": "Quantum Computing R&D",
        "naics": "541715",
        "annual_revenue_usd": 42_000_000.0,
        "employees": 180,
        "account_manager": "Lin Park",
        "sales_engineer": "Ravi Chandra (RF / Cryo)",
        "customer_since": "2021-09-01",
        "status": "active",
        "sla_tier": "Silver",
        "duns": "92-118-2245",
        "tax_id": "47-3399218",
        "payment_terms": "Net 30",
        "credit_limit": 350_000.0,
        "default_currency": "USD",
        "default_incoterms": "FOB Origin",
        "addresses": [
            {"type": "headquarters", "line1": "1235 Innovation Way", "line2": "Building Q-Lab 7", "city": "Boulder", "region": "CO", "country": "US", "postal": "80303"},
        ],
        "contacts": [
            {"name": "Dr. Priya Iyer", "title": "Lab PI — Qubit Control", "role": "lab_ops", "email": "lab.ops@vertex-quantum.com", "phone": "+1 303 555 0144", "is_primary": True},
        ],
    },
    {
        "code": "FINOLA-EU-061",
        "name": "Finolab Electronics GmbH",
        "legal_entity": "Finolab Electronics GmbH & Co. KG",
        "region": "EMEA",
        "language": "en",
        "email": "orders@finolab-electronics.de",
        "vertical": "industrial",
        "compliance": ["ISO_17025", "ISO_9001"],
        "industry": "Industrial T&M Services",
        "naics": "541380",
        "annual_revenue_usd": 168_000_000.0,
        "employees": 540,
        "account_manager": "Dirk Hoffmann",
        "sales_engineer": "Helena Krüger",
        "customer_since": "2009-04-12",
        "status": "active",
        "sla_tier": "Gold",
        "duns": "DE-7711-3398",
        "tax_id": "DE-289173447",
        "payment_terms": "Net 45",
        "credit_limit": 900_000.0,
        "default_currency": "EUR",
        "default_incoterms": "DDP",
        "addresses": [
            {"type": "headquarters", "line1": "Hansaring 88", "city": "Köln", "region": "NRW", "country": "DE", "postal": "50670"},
            {"type": "ship_to", "line1": "Industriepark Rhein — Halle 4", "city": "Köln", "region": "NRW", "country": "DE", "postal": "50670"},
        ],
        "contacts": [
            {"name": "Linda Voss", "title": "Calibration Lab Lead", "role": "lab_ops", "email": "linda.voss@finolab-electronics.de", "phone": "+49 221 555 0144", "is_primary": True},
            {"name": "Markus Klein", "title": "Procurement Manager", "role": "procurement", "email": "orders@finolab-electronics.de", "phone": "+49 221 555 0177"},
        ],
    },
]


PRODUCTS = [
    {"sku": "N5247B-419", "description": "PNA-X Microwave Network Analyzer, 67 GHz, 4-port, with frequency-converter + receiver options", "list_price": 218500.0, "family": "VNA", "category": "RF/Microwave", "mpn": "N5247B-419", "lifecycle_status": "active", "lead_time_weeks": 16, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "3A002.f", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "hazmat": False, "weight_kg": 35.4},
    {"sku": "E5080B-2H285", "description": "ENA Vector Network Analyzer, 8.5 GHz, 4-port", "list_price": 39800.0, "family": "VNA", "category": "RF/Microwave", "mpn": "E5080B-2H285", "lifecycle_status": "active", "lead_time_weeks": 8, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "weight_kg": 18.5},
    {"sku": "E5071C-485", "description": "ENA Network Analyzer, 8.5 GHz, 4-port (legacy / EOL)", "list_price": 38500.0, "family": "VNA", "category": "RF/Microwave", "mpn": "E5071C-485", "lifecycle_status": "eol_announced", "lifecycle_eol_date": "2027-06-30", "successor_sku": "E5080B-2H285", "lead_time_weeks": 14, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "weight_kg": 18.0},
    {"sku": "P9374A", "description": "Streamline USB VNA, 20 GHz, 2-port", "list_price": 22600.0, "family": "VNA", "category": "RF/Microwave", "mpn": "P9374A", "lifecycle_status": "active", "lead_time_weeks": 6, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "weight_kg": 0.85},
    {"sku": "N9020B-526", "description": "MXA Signal Analyzer, 26.5 GHz, with EVM/W-CDMA/5G NR personalities", "list_price": 88500.0, "family": "SA", "category": "RF/Microwave", "mpn": "N9020B-526", "lifecycle_status": "active", "lead_time_weeks": 10, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "9030.40.0000", "warranty_months": 12, "moq": 1, "weight_kg": 22.7},
    {"sku": "N9040B-550", "description": "UXA Signal Analyzer, 50 GHz, 510 MHz analysis bandwidth", "list_price": 196000.0, "family": "SA", "category": "RF/Microwave", "mpn": "N9040B-550", "lifecycle_status": "active", "lead_time_weeks": 14, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "3A002.f", "hs_code": "9030.40.0000", "warranty_months": 12, "moq": 1, "weight_kg": 28.0},
    {"sku": "N5183B-540", "description": "MXG Microwave Analog Signal Generator, 40 GHz", "list_price": 71500.0, "family": "SG", "category": "RF/Microwave", "mpn": "N5183B-540", "lifecycle_status": "active", "lead_time_weeks": 12, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "8543.20.0000", "warranty_months": 12, "moq": 1, "weight_kg": 22.0},
    {"sku": "M9384B-04F", "description": "VXG Vector Signal Generator, 44 GHz, 2-channel, 2 GHz modulation BW", "list_price": 168000.0, "family": "SG", "category": "RF/Microwave", "mpn": "M9384B-04F", "lifecycle_status": "active", "lead_time_weeks": 16, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "3A002.f", "hs_code": "8543.20.0000", "warranty_months": 12, "moq": 1, "weight_kg": 24.0},
    {"sku": "DSOX3024T", "description": "InfiniiVision 3000T Oscilloscope, 200 MHz, 4-Ch, capacitive touch", "list_price": 5990.0, "family": "OSC", "category": "Digital", "mpn": "DSOX3024T", "lifecycle_status": "active", "lead_time_weeks": 4, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "9030.20.0500", "warranty_months": 36, "moq": 1, "weight_kg": 4.5},
    {"sku": "MSOS804A", "description": "Infiniium S-Series Oscilloscope, 8 GHz, 4 analog + 16 digital", "list_price": 56400.0, "family": "OSC", "category": "Digital", "mpn": "MSOS804A", "lifecycle_status": "active", "lead_time_weeks": 8, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "9030.20.0500", "warranty_months": 12, "moq": 1, "weight_kg": 17.2},
    {"sku": "UXR0334A", "description": "Infiniium UXR Real-Time Oscilloscope, 33 GHz, 4-Ch, 128 GS/s", "list_price": 312000.0, "family": "OSC", "category": "Digital", "mpn": "UXR0334A", "lifecycle_status": "active", "lead_time_weeks": 18, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "3A002.a.5", "hs_code": "9030.20.0500", "warranty_months": 12, "moq": 1, "weight_kg": 38.5},
    {"sku": "N9912A-345", "description": "FieldFox Handheld RF Analyzer, 4 GHz, Combination NA/SA/CAT", "list_price": 14800.0, "family": "FieldFox", "category": "RF/Microwave", "mpn": "N9912A-345", "lifecycle_status": "active", "lead_time_weeks": 6, "calibration_interval_months": 24, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "weight_kg": 3.0},
    {"sku": "N9952A", "description": "FieldFox Handheld Microwave Analyzer, 50 GHz", "list_price": 68500.0, "family": "FieldFox", "category": "RF/Microwave", "mpn": "N9952A", "lifecycle_status": "active", "lead_time_weeks": 8, "calibration_interval_months": 24, "country_of_origin": "US", "eccn": "3A002.f", "hs_code": "9030.84.0080", "warranty_months": 12, "moq": 1, "weight_kg": 4.6},
    {"sku": "N6705C", "description": "DC Power Analyzer Mainframe, 4-slot", "list_price": 9100.0, "family": "DC", "category": "DC Power", "mpn": "N6705C", "lifecycle_status": "active", "lead_time_weeks": 4, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "8504.40.7000", "warranty_months": 36, "moq": 1, "weight_kg": 14.5},
    {"sku": "B2902B", "description": "Precision Source/Measure Unit, 2-Ch, 10 fA / 100 nV", "list_price": 8400.0, "family": "SMU", "category": "DC Power", "mpn": "B2902B", "lifecycle_status": "active", "lead_time_weeks": 4, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "9030.31.0000", "warranty_months": 36, "moq": 1, "weight_kg": 5.0},
    {"sku": "U4154B", "description": "AXIe Logic Analyzer, 136 channels, 4 GHz state", "list_price": 102000.0, "family": "LA", "category": "Digital", "mpn": "U4154B", "lifecycle_status": "mature", "lead_time_weeks": 10, "calibration_interval_months": 24, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "9030.20.0500", "warranty_months": 12, "moq": 1, "weight_kg": 9.8},
    {"sku": "33622A", "description": "Trueform Waveform Generator, 120 MHz, 2-Ch", "list_price": 6850.0, "family": "AWG", "category": "RF/Microwave", "mpn": "33622A", "lifecycle_status": "active", "lead_time_weeks": 4, "calibration_interval_months": 12, "country_of_origin": "MY", "eccn": "EAR99", "hs_code": "8543.20.0000", "warranty_months": 36, "moq": 1, "weight_kg": 3.5},
    {"sku": "M8040A", "description": "High-Performance BERT, 64 GBaud", "list_price": 425000.0, "family": "BERT", "category": "Digital", "mpn": "M8040A", "lifecycle_status": "active", "lead_time_weeks": 20, "calibration_interval_months": 12, "country_of_origin": "US", "eccn": "3A002.a.5", "hs_code": "8543.70.9650", "warranty_months": 12, "moq": 1, "weight_kg": 32.0},
    {"sku": "CAL-A2LA-1Y", "description": "Calibration Service - A2LA/ISO 17025 traceable, 1-year", "list_price": 1450.0, "family": "SVC", "category": "Service", "mpn": "CAL-A2LA-1Y", "lifecycle_status": "active", "lead_time_weeks": 2, "country_of_origin": "US", "eccn": "EAR99", "hs_code": None, "warranty_months": 0, "moq": 1},
    {"sku": "CAL-Z540-1Y", "description": "Calibration Service - Z540.3 compliant, 1-year, with as-found data", "list_price": 1850.0, "family": "SVC", "category": "Service", "mpn": "CAL-Z540-1Y", "lifecycle_status": "active", "lead_time_weeks": 2, "country_of_origin": "US", "eccn": "EAR99", "hs_code": None, "warranty_months": 0, "moq": 1},
    {"sku": "CAL-ANSI-1Y", "description": "Calibration Service - ANSI/NCSL Z540, 1-year, with as-found data", "list_price": 1650.0, "family": "SVC", "category": "Service", "mpn": "CAL-ANSI-1Y", "lifecycle_status": "active", "lead_time_weeks": 2, "country_of_origin": "US", "eccn": "EAR99", "hs_code": None, "warranty_months": 0, "moq": 1},
    {"sku": "WARR-EXT-3Y", "description": "Extended Warranty, additional 3-year coverage", "list_price": 3200.0, "family": "SVC", "category": "Service", "mpn": "WARR-EXT-3Y", "lifecycle_status": "active", "lead_time_weeks": 0, "country_of_origin": "US", "eccn": "EAR99", "hs_code": None, "warranty_months": 0, "moq": 1},
    {"sku": "85052D", "description": "3.5 mm Economy Calibration Kit, DC to 26.5 GHz", "list_price": 4750.0, "family": "ACC", "category": "Accessory", "mpn": "85052D", "lifecycle_status": "active", "lead_time_weeks": 6, "calibration_interval_months": 24, "country_of_origin": "US", "eccn": "EAR99", "hs_code": "9030.90.6800", "warranty_months": 12, "moq": 1, "weight_kg": 2.2},
]


VERTICAL_LABELS = {
    "aerospace_defense": "Aerospace & Defense",
    "semiconductor": "Semiconductor",
    "wireless_5g6g": "Wireless / 5G/6G",
    "automotive": "Automotive Electronics",
    "research": "Research",
    "industrial": "Industrial",
    "test_systems_integrator": "T&M Systems Integrator",
}


# Procedurally generated extras across AMS / EMEA / APAC / JP, plus
# distributors and magic SKUs. Hand-crafted records above stay first;
# generated extras append so that demo scenarios anchored on RTHN/BLUEH/
# TSMC/MERID/SAKURA continue to work unchanged.
from .catalog_extra import (
    CUSTOMERS_EXTRA,
    PRODUCTS_EXTRA,
    DISTRIBUTORS,
    MAGIC_SKUS,
)

CUSTOMERS = CUSTOMERS + CUSTOMERS_EXTRA
PRODUCTS = PRODUCTS + PRODUCTS_EXTRA
